import streamlit as st
import pickle
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from PIL import Image
from fpdf import FPDF
import tempfile
import os

# --- PAGE CONFIG ---
st.set_page_config(
    page_title="Ca' Foscari Loan Analytics",
    page_icon="🏛️",
    layout="wide"
)

# --- CUSTOM CSS FOR VISIBILITY ---
st.markdown("""
    <style>
    .stApp { background-color: #f4f7f6; }
    .result-card {
        background-color: #ffffff;
        padding: 25px;
        border-radius: 15px;
        border-left: 10px solid #800000;
        box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        margin-bottom: 20px;
    }
    [data-testid="stMetricLabel"] { color: #444444 !important; font-weight: bold !important; }
    [data-testid="stMetricValue"] { color: #800000 !important; font-size: 2.5rem !important; }
    .toc-link { text-decoration: none; color: #800000; font-weight: bold; }
    </style>
    """, unsafe_allow_html=True)

# --- LOAD ASSETS ---
@st.cache_resource
def load_assets():
    try:
        with open('scaler.pkl', 'rb') as f:
            scaler = pickle.load(f)
        with open('tuned_svm_model.pkl', 'rb') as f:
            model = pickle.load(f)
        return scaler, model
    except Exception:
        return None, None

scaler, model = load_assets()

# --- INIT SESSION STATE ---
# This prevents the app from resetting when the download button is clicked
if 'assessed' not in st.session_state:
    st.session_state['assessed'] = False

# --- PDF GENERATOR FUNCTION ---
def generate_pdf_report(inputs, pred, prob, features, weights):
    pdf = FPDF()
    pdf.add_page()
    
    # Header
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(0, 10, "Loan Default Risk Assessment Report", ln=True, align='C')
    pdf.ln(10)
    
    # Applicant Profile
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "Applicant Profile:", ln=True)
    pdf.set_font("Arial", '', 11)
    for key, val in inputs.items():
        pdf.cell(0, 8, f"{key}: {val}", ln=True)
    pdf.ln(5)
    
    # Assessment Result
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "Assessment Result:", ln=True)
    pdf.set_font("Arial", '', 11)
    status = "HIGH RISK (DEFAULT PREDICTED)" if pred == 1 else "APPROVED (LOW RISK)"
    pdf.cell(0, 8, f"Status: {status}", ln=True)
    pdf.cell(0, 8, f"Probability of Default: {prob:.2%}", ln=True)
    pdf.ln(5)
    
    # Explanation / Feature Importance
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "Model Explanation (Feature Impact):", ln=True)
    pdf.set_font("Arial", '', 11)
    pdf.multi_cell(0, 8, "The following shows how much each factor influenced the decision. Positive weights increase the risk of default, while negative weights decrease the risk.")
    
    impacts = sorted(zip(features, weights), key=lambda x: x[1], reverse=True)
    for feat, weight in impacts:
        impact_dir = "Increases Risk" if weight > 0 else "Decreases Risk"
        pdf.cell(0, 8, f"- {feat}: {weight:.4f} ({impact_dir})", ln=True)
        
    pdf.ln(15)
    pdf.set_font("Arial", 'I', 9)
    pdf.cell(0, 10, "Generated by Ca' Foscari Loan Analytics System.", ln=True)
    
    # Save to a temporary file to safely return bytes
    with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
        pdf.output(tmp.name)
        with open(tmp.name, "rb") as f:
            pdf_bytes = f.read()
    os.remove(tmp.name) # Clean up temp file
    
    return pdf_bytes

# --- SIDEBAR NAVIGATION ---
with st.sidebar:
    try:
        st.image("VSM.jpg", use_container_width=True)
    except:
        pass
    
    st.title("Navigation")
    st.markdown("""
    <ul style="list-style-type:none; padding:0;">
        <li><a class="toc-link" href="#single-assessment">🎯 Single Assessment</a></li>
        <li><a class="toc-link" href="#batch-upload">📂 Batch Upload</a></li>
        <li><a class="toc-link" href="#model-insights">📊 Model Insights</a></li>
    </ul>
    """, unsafe_allow_html=True)
    
    st.divider()
    if model:
        st.write(f"**Kernel:** {model.kernel.upper()}")
        st.write(f"**Iterations:** {model.n_iter_[0]}")

# --- MAIN PAGE ---
st.title("💰 Loan Default Risk Portal")

if scaler and model:
    tab1, tab2, tab3 = st.tabs(["Individual", "Batch", "Insights"])

    # --- TAB 1: INDIVIDUAL PREDICTION ---
    with tab1:
        st.markdown('<div id="single-assessment"></div>', unsafe_allow_html=True)
        col_in, col_res = st.columns([1.2, 1])
        
        with col_in:
            with st.container(border=True):
                st.subheader("Applicant Data")
                # Wrap inputs in a form so it doesn't predict on every keystroke
                with st.form("input_form"):
                    age = st.number_input("Age", 18, 100, 35)
                    income = st.number_input("Annual Income ($)", 0, 1000000, 50000)
                    credit = st.slider("Credit Score", 300, 850, 650)
                    dti = st.slider("DTI Ratio", 0.0, 1.0, 0.3)
                    
                    c1, c2 = st.columns(2)
                    job_yrs = c1.number_input("Years at Job", 0, 50, 5)
                    loans = c2.number_input("Existing Loans", 0, 20, 1)
                    
                    analyze_btn = st.form_submit_button("Run Risk Assessment", type="primary")

        # Execute Prediction and save to session state
        if analyze_btn:
            input_data = pd.DataFrame([[age, income, credit, job_yrs, loans, dti]], 
                                     columns=['Age', 'Annual_Income', 'Credit_Score', 'Years_at_Job', 'Existing_Loans', 'DTI_Ratio'])
            scaled = scaler.transform(input_data)
            
            # Save results to session state
            st.session_state['prob'] = model.predict_proba(scaled)[0][1]
            st.session_state['pred'] = model.predict(scaled)[0]
            st.session_state['inputs'] = {
                "Age": age, "Annual Income ($)": income, "Credit Score": credit, 
                "Years at Job": job_yrs, "Existing Loans": loans, "DTI Ratio": dti
            }
            st.session_state['assessed'] = True

        # Display results ONLY if an assessment has been run and saved in state
        with col_res:
            if st.session_state['assessed']:
                st.subheader("Risk Assessment")
                pred = st.session_state['pred']
                prob = st.session_state['prob']
                
                st.markdown(f"""
                    <div class="result-card">
                        <h3 style="margin-top:0; color:#444;">Analysis Summary</h3>
                        <p style="color:#666;">Status: <b style="color:{'#e74c3c' if pred==1 else '#27ae60'}">
                        {'DEFAULT RISK' if pred==1 else 'APPROVED'}</b></p>
                    </div>
                    """, unsafe_allow_html=True)
                
                st.metric(label="Probability of Default", value=f"{prob:.2%}")
                st.progress(prob)
                
                # Generate PDF Bytes
                pdf_data = generate_pdf_report(
                    inputs=st.session_state['inputs'], 
                    pred=pred, 
                    prob=prob, 
                    features=scaler.feature_names_in_, 
                    weights=model.coef_[0]
                )
                
                # Download Button (does not clear the screen now due to session state!)
                st.download_button(
                    label="📄 Download Assessment Report (PDF)",
                    data=pdf_data,
                    file_name="Risk_Assessment_Report.pdf",
                    mime="application/pdf",
                    type="primary"
                )
            else:
                st.info("👈 Enter applicant data and click 'Run Risk Assessment' to see results here.")

    # --- TAB 2: BATCH PROCESSING ---
    with tab2:
        st.markdown('<div id="batch-upload"></div>', unsafe_allow_html=True)
        st.subheader("📂 Batch Processing")
        uploaded_file = st.file_uploader("Upload CSV Data", type="csv")
        if uploaded_file:
            df = pd.read_csv(uploaded_file)
            required = ['Age', 'Annual_Income', 'Credit_Score', 'Years_at_Job', 'Existing_Loans', 'DTI_Ratio']
            if all(col in df.columns for col in required):
                batch_scaled = scaler.transform(df[required])
                df['Risk Score'] = model.predict_proba(batch_scaled)[:, 1]
                df['Decision'] = np.where(model.predict(batch_scaled) == 1, 'Deny', 'Approve')
                st.dataframe(df, use_container_width=True)
                csv = df.to_csv(index=False).encode('utf-8')
                st.download_button("Download Batch Results", csv, "batch_results.csv", "text/csv")
            else:
                st.error(f"Missing required columns. Please include: {required}")

    # --- TAB 3: INSIGHTS ---
    with tab3:
        st.markdown('<div id="model-insights"></div>', unsafe_allow_html=True)
        st.subheader("📊 Model Insights")
        st.info("""
        Inspired by the **Data Science for Finance** course at **Ca' Foscari University of Venice**.
        This project utilizes a Linear SVM model to classify credit risk based on six key financial metrics.
        """)
        
        weights = model.coef_[0]
        feats = scaler.feature_names_in_
        fig = go.Figure(go.Bar(x=weights, y=feats, orientation='h', marker_color='#800000'))
        fig.update_layout(title="Feature Influence on Default Risk", template="plotly_white")
        st.plotly_chart(fig, use_container_width=True)

else:
    st.error("Please ensure 'tuned_svm_model.pkl' and 'scaler.pkl' are uploaded.")
