# -*- coding: utf-8 -*-
"""Generation : Synthetic Data for Credit Analysis .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fmNamAKM2qlGlfv-PmlIVMZsSi8bD0Zg
"""

import warnings
warnings.filterwarnings('ignore')

# import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("whitegrid") # Set style for plots

# Set seed for reproducibility
np.random.seed(42)
n_customers = 20000

"""### **Create and engineering features:**"""

# 1. Generate Base Features
data = {
    'Customer_ID': range(1001, 1001 + n_customers),
    'Age': np.random.randint(18, 75, size=n_customers),
    'Annual_Income': np.random.lognormal(mean=11, sigma=0.5, size=n_customers).astype(int),
    'Credit_Score': np.random.randint(300, 850, size=n_customers),
    'Years_at_Job': np.random.randint(0, 40, size=n_customers),
    'Existing_Loans': np.random.randint(0, 5, size=n_customers)
}

# convert into a dataframe
df = pd.DataFrame(data)

df.head(5)

print(f"The shape of the data is:", df.shape)

# 2. Derive Logic-Based Features
# Debt-to-Income ratio (simulated)
df['DTI_Ratio'] = np.round(np.random.uniform(0.1, 0.6, size=n_customers), 2)

# Drop 'Customer_ID' before exporting to CSV as it's not a feature for modeling
df_to_export = df.drop(columns=['Customer_ID'])

# Export the DataFrame to a CSV file without the index
df_to_export.to_csv('loan_data.csv', index=False)

print("DataFrame exported to 'loan_data.csv' successfully, excluding 'Customer_ID'.")